# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ haveged_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - haveged
    - haveged-dependencies

- name: install additional
  ansible.builtin.apt:
    name: "{{ haveged_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - haveged
    - haveged-install

- name: update configuration file
  ansible.builtin.template:
    src: "{{ haveged_etc_default_file.lstrip('/') }}.j2"
    dest: "{{ haveged_etc_default_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart haveged
  tags:
    - configuration
    - haveged
    - haveged-configuration

- name: start and enable service
  ansible.builtin.service:
    name: haveged
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - haveged
    - haveged-start-enable-service
